engines:
  rubocop:
    enabled: true
    #checks:
    # Rubocop/Metrics/ClassLength:
    #   enabled: false
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
        #mass_threshold: 30
      - javascript
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  esling:
    enabled: true

ratings:
  paths:
  - "app/**"
  - "vendor/gems/**"
  - "**.rb"
exclude_paths:
  - "spec/**/*"
  - "**/spec/**/*"
  - "**/schema.rb"
  - "app/assets/javascripts/ractive.js"
  - "app/assets/javascripts/ractive-bootstrap.js"
  - "app/assets/javascripts/u2f-api.js"
  - "app/assets/javascripts/mock_yubikey.js"
  - "app/assets/javascripts/bootstrap-multimodal.js"
  - "**/*.gemspec"
  - "**/db/migrate/*"
  - "db/migrate/*"
